export const Countries = [
  // América
  { name: 'Canadá', code: 'CA', dialCode: '+1', emoji: '🇨🇦' },
  { name: 'Estados Unidos', code: 'US', dialCode: '+1', emoji: '🇺🇸' },
  { name: 'México', code: 'MX', dialCode: '+52', emoji: '🇲🇽' },
  { name: 'Belice', code: 'BZ', dialCode: '+501', emoji: '🇧🇿' },
  { name: 'Guatemala', code: 'GT', dialCode: '+502', emoji: '🇬🇹' },
  { name: 'El Salvador', code: 'SV', dialCode: '+503', emoji: '🇸🇻' },
  { name: 'Honduras', code: 'HN', dialCode: '+504', emoji: '🇭🇳' },
  { name: 'Nicaragua', code: 'NI', dialCode: '+505', emoji: '🇳🇮' },
  { name: 'Costa Rica', code: 'CR', dialCode: '+506', emoji: '🇨🇷' },
  { name: 'Panamá', code: 'PA', dialCode: '+507', emoji: '🇵🇦' },
  { name: 'Colombia', code: 'CO', dialCode: '+57', emoji: '🇨🇴' },
  { name: 'Venezuela', code: 'VE', dialCode: '+58', emoji: '🇻🇪' },
  { name: 'Ecuador', code: 'EC', dialCode: '+593', emoji: '🇪🇨' },
  { name: 'Perú', code: 'PE', dialCode: '+51', emoji: '🇵🇪' },
  { name: 'Bolivia', code: 'BO', dialCode: '+591', emoji: '🇧🇴' },
  { name: 'Chile', code: 'CL', dialCode: '+56', emoji: '🇨🇱' },
  { name: 'Argentina', code: 'AR', dialCode: '+54', emoji: '🇦🇷' },
  { name: 'Uruguay', code: 'UY', dialCode: '+598', emoji: '🇺🇾' },
  { name: 'Paraguay', code: 'PY', dialCode: '+595', emoji: '🇵🇾' },
  { name: 'Brasil', code: 'BR', dialCode: '+55', emoji: '🇧🇷' },
  { name: 'Cuba', code: 'CU', dialCode: '+53', emoji: '🇨🇺' },
  { name: 'República Dominicana', code: 'DO', dialCode: '+1', emoji: '🇩🇴' },
  { name: 'Haití', code: 'HT', dialCode: '+509', emoji: '🇭🇹' },
  { name: 'Puerto Rico', code: 'PR', dialCode: '+1', emoji: '🇵🇷' },
  { name: 'Jamaica', code: 'JM', dialCode: '+1 876', emoji: '🇯🇲' },
  { name: 'Trinidad y Tobago', code: 'TT', dialCode: '+1 868', emoji: '🇹🇹' },
  { name: 'Bahamas', code: 'BS', dialCode: '+1 242', emoji: '🇧🇸' },
  { name: 'Barbados', code: 'BB', dialCode: '+1 246', emoji: '🇧🇧' },
  { name: 'Guyana', code: 'GY', dialCode: '+592', emoji: '🇬🇾' },
  { name: 'Surinam', code: 'SR', dialCode: '+597', emoji: '🇸🇷' },
  { name: 'Antigua y Barbuda', code: 'AG', dialCode: '+1 268', emoji: '🇦🇬' },
  { name: 'Granada', code: 'GD', dialCode: '+1 473', emoji: '🇬🇩' },
  { name: 'San Cristóbal y Nieves', code: 'KN', dialCode: '+1 869', emoji: '🇰🇳' },
  { name: 'Santa Lucía', code: 'LC', dialCode: '+1 758', emoji: '🇱🇨' },
  { name: 'San Vicente y las Granadinas', code: 'VC', dialCode: '+1 784', emoji: '🇻🇨' },
  { name: 'Aruba', code: 'AW', dialCode: '+297', emoji: '🇦🇼' },
  { name: 'Curazao', code: 'CW', dialCode: '+599', emoji: '🇨🇼' },
  { name: 'Guayana Francesa', code: 'GF', dialCode: '+594', emoji: '🇬🇫' },
  { name: 'Guadalupe', code: 'GP', dialCode: '+590', emoji: '🇬🇵' },
  { name: 'Martinica', code: 'MQ', dialCode: '+596', emoji: '🇲🇶' },
  { name: 'San Bartolomé', code: 'BL', dialCode: '+590', emoji: '🇧🇱' },
  { name: 'San Martín', code: 'MF', dialCode: '+590', emoji: '🇲🇫' },
  { name: 'Islas Turcas y Caicos', code: 'TC', dialCode: '+1 649', emoji: '🇹🇨' },
  { name: 'Islas Vírgenes Británicas', code: 'VG', dialCode: '+1 284', emoji: '🇻🇬' },
  { name: 'Islas Vírgenes de los Estados Unidos', code: 'VI', dialCode: '+1 340', emoji: '🇻🇮' },
  { name: 'Anguila', code: 'AI', dialCode: '+1 264', emoji: '🇦🇮' },
  { name: 'Montserrat', code: 'MS', dialCode: '+1 664', emoji: '🇲🇸' },
  { name: 'San Pedro y Miquelón', code: 'PM', dialCode: '+508', emoji: '🇵🇲' },
  { name: 'Islas Caimán', code: 'KY', dialCode: '+1 345', emoji: '🇰🇾' },
  { name: 'Bermudas', code: 'BM', dialCode: '+1 441', emoji: '🇧🇲' },
  { name: 'Groenlandia', code: 'GL', dialCode: '+299', emoji: '🇬🇱' },

  // Europa
  { name: 'Albania', code: 'AL', dialCode: '+355', emoji: '🇦🇱' },
  { name: 'Alemania', code: 'DE', dialCode: '+49', emoji: '🇩🇪' },
  { name: 'Andorra', code: 'AD', dialCode: '+376', emoji: '🇦🇩' },
  { name: 'Austria', code: 'AT', dialCode: '+43', emoji: '🇦🇹' },
  { name: 'Bielorrusia', code: 'BY', dialCode: '+375', emoji: '🇧🇾' },
  { name: 'Bélgica', code: 'BE', dialCode: '+32', emoji: '🇧🇪' },
  { name: 'Bosnia y Herzegovina', code: 'BA', dialCode: '+387', emoji: '🇧🇦' },
  { name: 'Bulgaria', code: 'BG', dialCode: '+359', emoji: '🇧🇬' },
  { name: 'Chipre', code: 'CY', dialCode: '+357', emoji: '🇨🇾' },
  { name: 'Croacia', code: 'HR', dialCode: '+385', emoji: '🇭🇷' },
  { name: 'Dinamarca', code: 'DK', dialCode: '+45', emoji: '🇩🇰' },
  { name: 'Eslovaquia', code: 'SK', dialCode: '+421', emoji: '🇸🇰' },
  { name: 'Eslovenia', code: 'SI', dialCode: '+386', emoji: '🇸🇮' },
  { name: 'España', code: 'ES', dialCode: '+34', emoji: '🇪🇸' },
  { name: 'Estonia', code: 'EE', dialCode: '+372', emoji: '🇪🇪' },
  { name: 'Finlandia', code: 'FI', dialCode: '+358', emoji: '🇫🇮' },
  { name: 'Francia', code: 'FR', dialCode: '+33', emoji: '🇫🇷' },
  { name: 'Georgia', code: 'GE', dialCode: '+995', emoji: '🇬🇪' },
  { name: 'Grecia', code: 'GR', dialCode: '+30', emoji: '🇬🇷' },
  { name: 'Hungría', code: 'HU', dialCode: '+36', emoji: '🇭🇺' },
  { name: 'Irlanda', code: 'IE', dialCode: '+353', emoji: '🇮🇪' },
  { name: 'Islandia', code: 'IS', dialCode: '+354', emoji: '🇮🇸' },
  { name: 'Italia', code: 'IT', dialCode: '+39', emoji: '🇮🇹' },
  { name: 'Kazajistán', code: 'KZ', dialCode: '+7', emoji: '🇰🇿' },
  { name: 'Kosovo', code: 'XK', dialCode: '+383', emoji: '🇽🇰' },
  { name: 'Letonia', code: 'LV', dialCode: '+371', emoji: '🇱🇻' },
  { name: 'Liechtenstein', code: 'LI', dialCode: '+423', emoji: '🇱🇮' },
  { name: 'Lituania', code: 'LT', dialCode: '+370', emoji: '🇱🇹' },
  { name: 'Luxemburgo', code: 'LU', dialCode: '+352', emoji: '🇱🇺' },
  { name: 'Malta', code: 'MT', dialCode: '+356', emoji: '🇲🇹' },
  { name: 'Moldavia', code: 'MD', dialCode: '+373', emoji: '🇲🇩' },
  { name: 'Mónaco', code: 'MC', dialCode: '+377', emoji: '🇲🇨' },
  { name: 'Montenegro', code: 'ME', dialCode: '+382', emoji: '🇲🇪' },
  { name: 'Macedonia del Norte', code: 'MK', dialCode: '+389', emoji: '🇲🇰' },
  { name: 'Noruega', code: 'NO', dialCode: '+47', emoji: '🇳🇴' },
  { name: 'Países Bajos', code: 'NL', dialCode: '+31', emoji: '🇳🇱' },
  { name: 'Polonia', code: 'PL', dialCode: '+48', emoji: '🇵🇱' },
  { name: 'Portugal', code: 'PT', dialCode: '+351', emoji: '🇵🇹' },
  { name: 'Reino Unido', code: 'GB', dialCode: '+44', emoji: '🇬🇧' },
  { name: 'República Checa', code: 'CZ', dialCode: '+420', emoji: '🇨🇿' },
  { name: 'Rumanía', code: 'RO', dialCode: '+40', emoji: '🇷🇴' },
  { name: 'Rusia', code: 'RU', dialCode: '+7', emoji: '🇷🇺' },
  { name: 'San Marino', code: 'SM', dialCode: '+378', emoji: '🇸🇲' },
  { name: 'Serbia', code: 'RS', dialCode: '+381', emoji: '🇷🇸' },
  { name: 'Suecia', code: 'SE', dialCode: '+46', emoji: '🇸🇪' },
  { name: 'Suiza', code: 'CH', dialCode: '+41', emoji: '🇨🇭' },
  { name: 'Turquía', code: 'TR', dialCode: '+90', emoji: '🇹🇷' },
  { name: 'Ucrania', code: 'UA', dialCode: '+380', emoji: '🇺🇦' },
  { name: 'Ciudad del Vaticano', code: 'VA', dialCode: '+3906698', emoji: '🇻🇦' },

  //Asia
  { name: 'Afganistán', code: 'AF', dialCode: '+93', emoji: '🇦🇫' },
  { name: 'Arabia Saudita', code: 'SA', dialCode: '+966', emoji: '🇸🇦' },
  { name: 'Armenia', code: 'AM', dialCode: '+374', emoji: '🇦🇲' },
  { name: 'Azerbaiyán', code: 'AZ', dialCode: '+994', emoji: '🇦🇿' },
  { name: 'Baréin', code: 'BH', dialCode: '+973', emoji: '🇧🇭' },
  { name: 'Bangladés', code: 'BD', dialCode: '+880', emoji: '🇧🇩' },
  { name: 'Bután', code: 'BT', dialCode: '+975', emoji: '🇧🇹' },
  { name: 'Brunéi', code: 'BN', dialCode: '+673', emoji: '🇧🇳' },
  { name: 'Camboya', code: 'KH', dialCode: '+855', emoji: '🇰🇭' },
  { name: 'Catar', code: 'QA', dialCode: '+974', emoji: '🇶🇦' },
  { name: 'China', code: 'CN', dialCode: '+86', emoji: '🇨🇳' },
  { name: 'Chipre', code: 'CY', dialCode: '+357', emoji: '🇨🇾' },
  { name: 'Corea del Norte', code: 'KP', dialCode: '+850', emoji: '🇰🇵' },
  { name: 'Corea del Sur', code: 'KR', dialCode: '+82', emoji: '🇰🇷' },
  { name: 'Emiratos Árabes Unidos', code: 'AE', dialCode: '+971', emoji: '🇦🇪' },
  { name: 'Filipinas', code: 'PH', dialCode: '+63', emoji: '🇵🇭' },
  { name: 'Georgia', code: 'GE', dialCode: '+995', emoji: '🇬🇪' },
  { name: 'India', code: 'IN', dialCode: '+91', emoji: '🇮🇳' },
  { name: 'Indonesia', code: 'ID', dialCode: '+62', emoji: '🇮🇩' },
  { name: 'Irán', code: 'IR', dialCode: '+98', emoji: '🇮🇷' },
  { name: 'Irak', code: 'IQ', dialCode: '+964', emoji: '🇮🇶' },
  { name: 'Israel', code: 'IL', dialCode: '+972', emoji: '🇮🇱' },
  { name: 'Japón', code: 'JP', dialCode: '+81', emoji: '🇯🇵' },
  { name: 'Jordania', code: 'JO', dialCode: '+962', emoji: '🇯🇴' },
  { name: 'Kazajistán', code: 'KZ', dialCode: '+7', emoji: '🇰🇿' },
  { name: 'Kirguistán', code: 'KG', dialCode: '+996', emoji: '🇰🇬' },
  { name: 'Kuwait', code: 'KW', dialCode: '+965', emoji: '🇰🇼' },
  { name: 'Laos', code: 'LA', dialCode: '+856', emoji: '🇱🇦' },
  { name: 'Líbano', code: 'LB', dialCode: '+961', emoji: '🇱🇧' },
  { name: 'Malasia', code: 'MY', dialCode: '+60', emoji: '🇲🇾' },
  { name: 'Maldivas', code: 'MV', dialCode: '+960', emoji: '🇲🇻' },
  { name: 'Mongolia', code: 'MN', dialCode: '+976', emoji: '🇲🇳' },
  { name: 'Myanmar (Birmania)', code: 'MM', dialCode: '+95', emoji: '🇲🇲' },
  { name: 'Nepal', code: 'NP', dialCode: '+977', emoji: '🇳🇵' },
  { name: 'Omán', code: 'OM', dialCode: '+968', emoji: '🇴🇲' },
  { name: 'Pakistán', code: 'PK', dialCode: '+92', emoji: '🇵🇰' },
  { name: 'Palestina', code: 'PS', dialCode: '+970', emoji: '🇵🇸' },
  { name: 'Singapur', code: 'SG', dialCode: '+65', emoji: '🇸🇬' },
  { name: 'Siria', code: 'SY', dialCode: '+963', emoji: '🇸🇾' },
  { name: 'Sri Lanka', code: 'LK', dialCode: '+94', emoji: '🇱🇰' },
  { name: 'Tailandia', code: 'TH', dialCode: '+66', emoji: '🇹🇭' },
  { name: 'Tayikistán', code: 'TJ', dialCode: '+992', emoji: '🇹🇯' },
  { name: 'Timor Oriental', code: 'TL', dialCode: '+670', emoji: '🇹🇱' },
  { name: 'Turkmenistán', code: 'TM', dialCode: '+993', emoji: '🇹🇲' },
  { name: 'Uzbekistán', code: 'UZ', dialCode: '+998', emoji: '🇺🇿' },
  { name: 'Vietnam', code: 'VN', dialCode: '+84', emoji: '🇻🇳' },
  { name: 'Yemen', code: 'YE', dialCode: '+967', emoji: '🇾🇪' },

  // África
  { name: 'Angola', code: 'AO', dialCode: '+244', emoji: '🇦🇴' },
  { name: 'Argelia', code: 'DZ', dialCode: '+213', emoji: '🇩🇿' },
  { name: 'Benín', code: 'BJ', dialCode: '+229', emoji: '🇧🇯' },
  { name: 'Botsuana', code: 'BW', dialCode: '+267', emoji: '🇧🇼' },
  { name: 'Burkina Faso', code: 'BF', dialCode: '+226', emoji: '🇧🇫' },
  { name: 'Burundi', code: 'BI', dialCode: '+257', emoji: '🇧🇮' },
  { name: 'Cabo Verde', code: 'CV', dialCode: '+238', emoji: '🇨🇻' },
  { name: 'Camerún', code: 'CM', dialCode: '+237', emoji: '🇨🇲' },
  { name: 'Chad', code: 'TD', dialCode: '+235', emoji: '🇹🇩' },
  { name: 'Comoras', code: 'KM', dialCode: '+269', emoji: '🇰🇲' },
  { name: 'Costa de Marfil', code: 'CI', dialCode: '+225', emoji: '🇨🇮' },
  { name: 'Egipto', code: 'EG', dialCode: '+20', emoji: '🇪🇬' },
  { name: 'Eritrea', code: 'ER', dialCode: '+291', emoji: '🇪🇷' },
  { name: 'Etiopía', code: 'ET', dialCode: '+251', emoji: '🇪🇹' },
  { name: 'Gabón', code: 'GA', dialCode: '+241', emoji: '🇬🇦' },
  { name: 'Gambia', code: 'GM', dialCode: '+220', emoji: '🇬🇲' },
  { name: 'Ghana', code: 'GH', dialCode: '+233', emoji: '🇬🇭' },
  { name: 'Guinea', code: 'GN', dialCode: '+224', emoji: '🇬🇳' },
  { name: 'Guinea-Bisáu', code: 'GW', dialCode: '+245', emoji: '🇬🇼' },
  { name: 'Guinea Ecuatorial', code: 'GQ', dialCode: '+240', emoji: '🇬🇶' },
  { name: 'Kenia', code: 'KE', dialCode: '+254', emoji: '🇰🇪' },
  { name: 'Lesoto', code: 'LS', dialCode: '+266', emoji: '🇱🇸' },
  { name: 'Liberia', code: 'LR', dialCode: '+231', emoji: '🇱🇷' },
  { name: 'Libia', code: 'LY', dialCode: '+218', emoji: '🇱🇾' },
  { name: 'Madagascar', code: 'MG', dialCode: '+261', emoji: '🇲🇬' },
  { name: 'Malaui', code: 'MW', dialCode: '+265', emoji: '🇲🇼' },
  { name: 'Mali', code: 'ML', dialCode: '+223', emoji: '🇲🇱' },
  { name: 'Marruecos', code: 'MA', dialCode: '+212', emoji: '🇲🇦' },
  { name: 'Mauricio', code: 'MU', dialCode: '+230', emoji: '🇲🇺' },
  { name: 'Mauritania', code: 'MR', dialCode: '+222', emoji: '🇲🇷' },
  { name: 'Mozambique', code: 'MZ', dialCode: '+258', emoji: '🇲🇿' },
  { name: 'Namibia', code: 'NA', dialCode: '+264', emoji: '🇳🇦' },
  { name: 'Níger', code: 'NE', dialCode: '+227', emoji: '🇳🇪' },
  { name: 'Nigeria', code: 'NG', dialCode: '+234', emoji: '🇳🇬' },
  { name: 'República Centroafricana', code: 'CF', dialCode: '+236', emoji: '🇨🇫' },
  { name: 'República del Congo', code: 'CG', dialCode: '+242', emoji: '🇨🇬' },
  { name: 'República Democrática del Congo', code: 'CD', dialCode: '+243', emoji: '🇨🇩' },
  { name: 'Ruanda', code: 'RW', dialCode: '+250', emoji: '🇷🇼' },
  { name: 'Santo Tomé y Príncipe', code: 'ST', dialCode: '+239', emoji: '🇸🇹' },
  { name: 'Senegal', code: 'SN', dialCode: '+221', emoji: '🇸🇳' },
  { name: 'Seychelles', code: 'SC', dialCode: '+248', emoji: '🇸🇨' },
  { name: 'Sierra Leona', code: 'SL', dialCode: '+232', emoji: '🇸🇱' },
  { name: 'Somalia', code: 'SO', dialCode: '+252', emoji: '🇸🇴' },
  { name: 'Sudáfrica', code: 'ZA', dialCode: '+27', emoji: '🇿🇦' },
  { name: 'Sudán', code: 'SD', dialCode: '+249', emoji: '🇸🇩' },
  { name: 'Sudán del Sur', code: 'SS', dialCode: '+211', emoji: '🇸🇸' },
  { name: 'Suazilandia', code: 'SZ', dialCode: '+268', emoji: '🇸🇿' },
  { name: 'Tanzania', code: 'TZ', dialCode: '+255', emoji: '🇹🇿' },
  { name: 'Togo', code: 'TG', dialCode: '+228', emoji: '🇹🇬' },
  { name: 'Túnez', code: 'TN', dialCode: '+216', emoji: '🇹🇳' },
  { name: 'Uganda', code: 'UG', dialCode: '+256', emoji: '🇺🇬' },
  { name: 'Yibuti', code: 'DJ', dialCode: '+253', emoji: '🇩🇯' },
  { name: 'Zambia', code: 'ZM', dialCode: '+260', emoji: '🇿🇲' },
  { name: 'Zimbabue', code: 'ZW', dialCode: '+263', emoji: '🇿🇼' },

  // Oceanía
  { name: 'Australia', code: 'AU', dialCode: '+61', emoji: '🇦🇺' },
  { name: 'Fiyi', code: 'FJ', dialCode: '+679', emoji: '🇫🇯' },
  { name: 'Kiribati', code: 'KI', dialCode: '+686', emoji: '🇰🇮' },
  { name: 'Islas Marshall', code: 'MH', dialCode: '+692', emoji: '🇲🇭' },
  { name: 'Micronesia (Estados Federados de)', code: 'FM', dialCode: '+691', emoji: '🇫🇲' },
  { name: 'Nauru', code: 'NR', dialCode: '+674', emoji: '🇳🇷' },
  { name: 'Nueva Zelanda', code: 'NZ', dialCode: '+64', emoji: '🇳🇿' },
  { name: 'Palaos', code: 'PW', dialCode: '+680', emoji: '🇵🇼' },
  { name: 'Papúa Nueva Guinea', code: 'PG', dialCode: '+675', emoji: '🇵🇬' },
  { name: 'Samoa', code: 'WS', dialCode: '+685', emoji: '🇼🇸' },
  { name: 'Islas Salomón', code: 'SB', dialCode: '+677', emoji: '🇸🇧' },
  { name: 'Tonga', code: 'TO', dialCode: '+676', emoji: '🇹🇴' },
  { name: 'Tuvalu', code: 'TV', dialCode: '+688', emoji: '🇹🇻' },
  { name: 'Vanuatu', code: 'VU', dialCode: '+678', emoji: '🇻🇺' },

  // Territorios y otras entidades:
  { name: 'Samoa Americana', code: 'AS', dialCode: '+1 684', emoji: '🇦🇸' },
  { name: 'Islas Cook', code: 'CK', dialCode: '+682', emoji: '🇨🇰' },
  { name: 'Polinesia Francesa', code: 'PF', dialCode: '+689', emoji: '🇵🇫' },
  { name: 'Guam', code: 'GU', dialCode: '+1 671', emoji: '🇬🇺' },
  { name: 'Nueva Caledonia', code: 'NC', dialCode: '+687', emoji: '🇳🇨' },
  { name: 'Niue', code: 'NU', dialCode: '+683', emoji: '🇳🇺' },
  { name: 'Tokelau', code: 'TK', dialCode: '+690', emoji: '🇹🇰' },
  { name: 'Wallis y Futuna', code: 'WF', dialCode: '+681', emoji: '🇼🇫' }
];
